

convert:
	python convert.py

down:
	kompose -f docker-compose-for-kompose.yml down

up:
	kompose -f docker-compose-for-kompose.yml up

up_wo_pv:
	kompose -f docker-compose-for-kompose.yml up --emptyvols
