<?xml version="1.0"?>
<job_conf>
    <plugins workers="8">
        <plugin id="sge" type="runner" load="galaxy.jobs.runners.drmaa:DRMAAJobRunner">
            <param id="drmaa_library_path">/usr/lib/gridengine-drmaa/lib/libdrmaa.so.1.0</param>
        </plugin>
    </plugins>
    <handlers>
        <handler id="main"/>
    </handlers>
    <destinations default="cluster">
        <destination id="cluster" runner="sge">
            <param id="embed_metadata_in_job">False</param>
        </destination>
    </destinations>
    <limits>
        <limit type="registered_user_concurrent_jobs">1</limit>
        <limit type="anonymous_user_concurrent_jobs">1</limit>
        <limit type="destination_user_concurrent_jobs">1</limit>
        <limit type="destination_total_concurrent_jobs">1</limit>
        <limit type="unregistered_user_concurrent_jobs">1</limit>
    </limits>
</job_conf>
